### ISSUE TITLE
Wanted to try this out

### ISSUE THREAD

**Issue by MostHated** [simeonradivoev/UI-Node-Editor#1]
Hey there,
    I thought this looked pretty interesting and wanted to see what it was all about. I first just downloaded the zip and put it in a project but it kept saying nodeeditor was missing, so I went to just clone it to my pc but then it said I don't have permission to do that.

Thanks
-MH

**Comment by simeonradivoev** [comment]
Old post. If anyone stumbles on it. Node editor submodule needs to be initialized.
